
#ifndef __GPIO_H__
#define __GPIO_H__

/* Includes ------------------------------------------------------------------*/
#include <config.h>

// ** LED IO ** //
#define LED_GREEN_PORT GPIOC
#define LED_GREEN_PIN GPIO_Pin_7
#define LED_GREEN_H GPIO_SetBits(LED_GREEN_PORT, LED_GREEN_PIN)
#define LED_GREEN_L GPIO_ResetBits(LED_GREEN_PORT, LED_GREEN_PIN)
#define LED_GREEN_TOGGLEBITS GPIO_ToggleBits(LED_GREEN_PORT, LED_GREEN_PIN)

// ** KEY IO ** //
#define FUNC_KEY_PORT GPIOG
#define FUNC_KEY_PIN GPIO_Pin_7
#define READ_FUNC_KEY_STATUS GPIO_ReadInputDataBit(FUNC_KEY_PORT, FUNC_KEY_PIN)

#define RST_KEY_PORT GPIOD
#define RST_KEY_PIN GPIO_Pin_6
#define READ_RST_KEY_STATUS GPIO_ReadInputDataBit(RST_KEY_PORT, RST_KEY_PIN)

#define BAT_CTRL_PORT GPIOC
#define BAT_CTRL_PIN GPIO_Pin_14
#define BAT_CTRL_H GPIO_SetBits(BAT_CTRL_PORT, BAT_CTRL_PIN)
#define BAT_CTRL_L GPIO_ResetBits(BAT_CTRL_PORT, BAT_CTRL_PIN)

// ** LoRaWAN ** //
#define LoRaWAN_MODE_PIN GPIO_Pin_4
#define LoRaWAN_MODE_PORT GPIOC

#define LoRaWAN_BUSY_PIN GPIO_Pin_5
#define LoRaWAN_BUSY_PORT GPIOC

#define LoRaWAN_NRST_PIN GPIO_Pin_6
#define LoRaWAN_NRST_PORT GPIOC

#define LoRaWAN_STAT_PIN GPIO_Pin_3
#define LoRaWAN_STAT_PORT GPIOC

#define LoRaWAN_WAKE_PIN GPIO_Pin_2
#define LoRaWAN_WAKE_PORT GPIOC

// ** LED Drive ** //
#define MBI5120_SDI_PORT GPIOF
#define MBI5120_SDI_PIN GPIO_Pin_12

#define MBI5120_CLK_PORT GPIOF
#define MBI5120_CLK_PIN GPIO_Pin_14

#define MBI5120_LE_PORT GPIOF
#define MBI5120_LE_PIN GPIO_Pin_15

#define MBI5120_OE_PORT GPIOF
#define MBI5120_OE_PIN GPIO_Pin_13

#define MBI5120_PWR_PORT GPIOE
#define MBI5120_PWR_PIN GPIO_Pin_8

#define MBI5120_SDI_L GPIO_ResetBits(MBI5120_SDI_PORT, MBI5120_SDI_PIN)
#define MBI5120_SDI_H GPIO_SetBits(MBI5120_SDI_PORT, MBI5120_SDI_PIN)

#define MBI5120_CLK_L GPIO_ResetBits(MBI5120_CLK_PORT, MBI5120_CLK_PIN)
#define MBI5120_CLK_H GPIO_SetBits(MBI5120_CLK_PORT, MBI5120_CLK_PIN)

#define MBI5120_LE_L GPIO_ResetBits(MBI5120_LE_PORT, MBI5120_LE_PIN)
#define MBI5120_LE_H GPIO_SetBits(MBI5120_LE_PORT, MBI5120_LE_PIN)

#define MBI5120_OE_L GPIO_ResetBits(MBI5120_OE_PORT, MBI5120_OE_PIN)
#define MBI5120_OE_H GPIO_SetBits(MBI5120_OE_PORT, MBI5120_OE_PIN)

#define MBI5120_PWR_L GPIO_ResetBits(MBI5120_PWR_PORT, MBI5120_PWR_PIN)
#define MBI5120_PWR_H GPIO_SetBits(MBI5120_PWR_PORT, MBI5120_PWR_PIN)

// ** Motor Drive ** //
#define MOTOR_INA_PORT GPIOD
#define MOTOR_INA_PIN GPIO_Pin_7

#define MOTOR_INB_PORT GPIOD
#define MOTOR_INB_PIN GPIO_Pin_8

#define MOTOR_INA_L GPIO_ResetBits(MOTOR_INA_PORT, MOTOR_INA_PIN)
#define MOTOR_INA_H GPIO_SetBits(MOTOR_INA_PORT, MOTOR_INA_PIN)

#define MOTOR_INB_L GPIO_ResetBits(MOTOR_INB_PORT, MOTOR_INB_PIN)
#define MOTOR_INB_H GPIO_SetBits(MOTOR_INB_PORT, MOTOR_INB_PIN)

#define TCH_IIC_EN_PORT GPIOE
#define TCH_IIC_EN_PIN GPIO_Pin_3
#define TCH_IIC_EN_H GPIO_SetBits(TCH_IIC_EN_PORT, TCH_IIC_EN_PIN)
#define TCH_IIC_EN_L GPIO_ResetBits(TCH_IIC_EN_PORT, TCH_IIC_EN_PIN)
#define TCH_IIC_EN_TOGGLEBITS GPIO_ToggleBits(TCH_IIC_EN_PORT, TCH_IIC_EN_PIN)

#define TCH_IRQ_PORT GPIOE
#define TCH_IRQ_PIN GPIO_Pin_4
#define READ_TCH_IRQ GPIO_ReadInputDataBit(TCH_IRQ_PORT, TCH_IRQ_PIN)

#define TCH_SCT_PORT GPIOE
#define TCH_SCT_PIN GPIO_Pin_5
#define TCH_SCT_H GPIO_SetBits(TCH_SCT_PORT, TCH_SCT_PIN)
#define TCH_SCT_L GPIO_ResetBits(TCH_SCT_PORT, TCH_SCT_PIN)
#define TCH_SCT_TOGGLEBITS GPIO_ToggleBits(TCH_SCT_PORT, TCH_SCT_PIN)

#define TCH_RST_PORT GPIOE
#define TCH_RST_PIN GPIO_Pin_6
#define TCH_RST_H GPIO_SetBits(TCH_RST_PORT, TCH_RST_PIN)
#define TCH_RST_L GPIO_ResetBits(TCH_RST_PORT, TCH_RST_PIN)
#define TCH_RST_TOGGLEBITS GPIO_ToggleBits(TCH_RST_PORT, TCH_RST_PIN)

#define SPI_FLASH_CS_PORT GPIOA
#define SPI_FLASH_CS_PIN GPIO_Pin_0
#define SPI_FLASH_CS_H GPIO_SetBits(SPI_FLASH_CS_PORT, SPI_FLASH_CS_PIN)
#define SPI_FLASH_CS_L GPIO_ResetBits(SPI_FLASH_CS_PORT, SPI_FLASH_CS_PIN)
#define SPI_FLASH_CS_OUT OutputIO(SPI_FLASH_CS_PORT, SPI_FLASH_CS_PIN, OUT_PUSHPULL)
#define SPI_FLASH_CS_IN InputtIO(SPI_FLASH_CS_PORT, SPI_FLASH_CS_PIN, IN_NORMAL)
#define READ_SPI_FLASH_CS_STATUS GPIO_ReadInputDataBit(SPI_FLASH_CS_PORT, SPI_FLASH_CS_PIN)

#define SPI_FLASH_CLK_PORT GPIOA
#define SPI_FLASH_CLK_PIN GPIO_Pin_1
#define SPI_FLASH_CLK_H GPIO_SetBits(SPI_FLASH_CLK_PORT, SPI_FLASH_CLK_PIN)
#define SPI_FLASH_CLK_L GPIO_ResetBits(SPI_FLASH_CLK_PORT, SPI_FLASH_CLK_PIN)
#define SPI_FLASH_CLK_OUT OutputIO(SPI_FLASH_CLK_PORT, SPI_FLASH_CLK_PIN, OUT_PUSHPULL)
#define SPI_FLASH_CLK_IN InputtIO(SPI_FLASH_CLK_PORT, SPI_FLASH_CLK_PIN, IN_NORMAL)
#define READ_SPI_FLASH_CLK_STATUS GPIO_ReadInputDataBit(SPI_FLASH_CLK_PORT, SPI_FLASH_CLK_PIN)

#define SPI_FLASH_MISO_PORT GPIOA
#define SPI_FLASH_MISO_PIN GPIO_Pin_2
#define SPI_FLASH_MISO_H GPIO_SetBits(SPI_FLASH_MISO_PORT, SPI_FLASH_MISO_PIN)
#define SPI_FLASH_MISO_L GPIO_ResetBits(SPI_FLASH_MISO_PORT, SPI_FLASH_MISO_PIN)
#define SPI_FLASH_MISO_OUT OutputIO(SPI_FLASH_MISO_PORT, SPI_FLASH_MISO_PIN, OUT_PUSHPULL)
#define SPI_FLASH_MISO_IN InputtIO(SPI_FLASH_MISO_PORT, SPI_FLASH_MISO_PIN, IN_NORMAL)
// #define SPI_FLASH_MISO_IN InputtIO(SPI_FLASH_MISO_PORT, SPI_FLASH_MISO_PIN, IN_PULLUP)
#define READ_SPI_FLASH_MISO_STATUS GPIO_ReadInputDataBit(SPI_FLASH_MISO_PORT, SPI_FLASH_MISO_PIN)

#define SPI_FLASH_MOSI_PORT GPIOA
#define SPI_FLASH_MOSI_PIN GPIO_Pin_3
#define SPI_FLASH_MOSI_H GPIO_SetBits(SPI_FLASH_MOSI_PORT, SPI_FLASH_MOSI_PIN)
#define SPI_FLASH_MOSI_L GPIO_ResetBits(SPI_FLASH_MOSI_PORT, SPI_FLASH_MOSI_PIN)
#define SPI_FLASH_MOSI_OUT OutputIO(SPI_FLASH_MOSI_PORT, SPI_FLASH_MOSI_PIN, OUT_PUSHPULL)
#define SPI_FLASH_MOSI_IN InputtIO(SPI_FLASH_MOSI_PORT, SPI_FLASH_MOSI_PIN, IN_NORMAL)
#define READ_SPI_FLASH_MOSI_STATUS GPIO_ReadInputDataBit(SPI_FLASH_MOSI_PORT, SPI_FLASH_MOSI_PIN)

#define SPI_FLASH_WP_PORT GPIOA
#define SPI_FLASH_WP_PIN GPIO_Pin_4
#define SPI_FLASH_WP_H GPIO_SetBits(SPI_FLASH_WP_PORT, SPI_FLASH_WP_PIN)
#define SPI_FLASH_WP_L GPIO_ResetBits(SPI_FLASH_WP_PORT, SPI_FLASH_WP_PIN)
#define SPI_FLASH_WP_OUT OutputIO(SPI_FLASH_WP_PORT, SPI_FLASH_WP_PIN, OUT_PUSHPULL)

#define CARD_IRQ_PORT GPIOB
#define CARD_IRQ_PIN GPIO_Pin_8
#define READ_CARD_IRQ GPIO_ReadInputDataBit(CARD_IRQ_PORT, CARD_IRQ_PIN)

#define CARD_RST_PORT GPIOB
#define CARD_RST_PIN GPIO_Pin_9
#define CARD_RST_H GPIO_SetBits(CARD_RST_PORT, CARD_RST_PIN)
#define CARD_RST_L GPIO_ResetBits(CARD_RST_PORT, CARD_RST_PIN)
#define CARD_RST_TOGGLEBITS GPIO_ToggleBits(CARD_RST_PORT, CARD_RST_PIN)

#define CARD_IIC_PORT GPIOB
#define CARD_IIC_PIN GPIO_Pin_10
#define CARD_IIC_H GPIO_SetBits(CARD_IIC_PORT, CARD_IIC_PIN)
#define CARD_IIC_L GPIO_ResetBits(CARD_IIC_PORT, CARD_IIC_PIN)
#define CARD_IIC_TOGGLEBITS GPIO_ToggleBits(CARD_IIC_PORT, CARD_IIC_PIN)

#define CARD_EA_PORT GPIOB
#define CARD_EA_PIN GPIO_Pin_11
#define CARD_EA_H GPIO_SetBits(CARD_EA_PORT, CARD_EA_PIN)
#define CARD_EA_L GPIO_ResetBits(CARD_EA_PORT, CARD_EA_PIN)
#define CARD_EA_TOGGLEBITS GPIO_ToggleBits(CARD_EA_PORT, CARD_EA_PIN)

#define CARD_NSS_PORT GPIOB
#define CARD_NSS_PIN GPIO_Pin_12
#define CARD_NSS_H GPIO_SetBits(CARD_NSS_PORT, CARD_NSS_PIN)
#define CARD_NSS_L GPIO_ResetBits(CARD_NSS_PORT, CARD_NSS_PIN)
#define CARD_NSS_TOGGLEBITS GPIO_ToggleBits(CARD_NSS_PORT, CARD_NSS_PIN)

#define CARD_SCK_PORT GPIOB
#define CARD_SCK_PIN GPIO_Pin_13
#define CARD_SCK_H GPIO_SetBits(CARD_SCK_PORT, CARD_SCK_PIN)
#define CARD_SCK_L GPIO_ResetBits(CARD_SCK_PORT, CARD_SCK_PIN)
#define CARD_SCK_TOGGLEBITS GPIO_ToggleBits(CARD_SCK_PORT, CARD_SCK_PIN)

#define CARD_MISO_PORT GPIOB
#define CARD_MISO_PIN GPIO_Pin_14
#define CARD_MISO_H GPIO_SetBits(CARD_MISO_PORT, CARD_MISO_PIN)
#define CARD_MISO_L GPIO_ResetBits(CARD_MISO_PORT, CARD_MISO_PIN)
#define CARD_MISO_TOGGLEBITS GPIO_ToggleBits(CARD_MISO_PORT, CARD_MISO_PIN)
#define READ_CARD_MISO GPIO_ReadInputDataBit(CARD_MISO_PORT, CARD_MISO_PIN)

#define CARD_MOSI_PORT GPIOB
#define CARD_MOSI_PIN GPIO_Pin_15
#define CARD_MOSI_H GPIO_SetBits(CARD_MOSI_PORT, CARD_MOSI_PIN)
#define CARD_MOSI_L GPIO_ResetBits(CARD_MOSI_PORT, CARD_MOSI_PIN)
#define CARD_MOSI_TOGGLEBITS GPIO_ToggleBits(CARD_MOSI_PORT, CARD_MOSI_PIN)

/* 指纹IO */
#define FINGER_DETECT_PORT GPIOE
#define FINGER_DETECT_PIN GPIO_Pin_2
#define FINGER_DETECT_H GPIO_SetBits(FINGER_DETECT_PORT, FINGER_DETECT_PIN)
#define FINGER_DETECT_L GPIO_ResetBits(FINGER_DETECT_PORT, FINGER_DETECT_PIN)
#define FINGER_DETECT_TOGGLEBITS GPIO_ToggleBits(FINGER_DETECT_PORT, FINGER_DETECT_PIN)
#define READ_FINGER_DETECT GPIO_ReadInputDataBit(FINGER_DETECT_PORT, FINGER_DETECT_PIN)

#define FINGER_POWER_PORT GPIOB
#define FINGER_POWER_PIN GPIO_Pin_5
#define FINGER_POWER_H GPIO_SetBits(FINGER_POWER_PORT, FINGER_POWER_PIN)
#define FINGER_POWER_L GPIO_ResetBits(FINGER_POWER_PORT, FINGER_POWER_PIN)
#define FINGER_POWER_TOGGLEBITS GPIO_ToggleBits(FINGER_POWER_PORT, FINGER_POWER_PIN)

// ** 语音IC ** //
#define SOUND_DATA_PORT GPIOC
#define SOUND_DATA_PIN GPIO_Pin_12
#define SOUND_DATA_H GPIO_SetBits(SOUND_DATA_PORT, SOUND_DATA_PIN)
#define SOUND_DATA_L GPIO_ResetBits(SOUND_DATA_PORT, SOUND_DATA_PIN)

#define SOUND_BUSY_PORT GPIOC
#define SOUND_BUSY_PIN GPIO_Pin_13
#define READ_SOUND_BUSY_STATUS GPIO_ReadInputDataBit(SOUND_BUSY_PORT, SOUND_BUSY_PIN)

// ** BLE ** //
#define BLE_STATUS_PORT GPIOA
#define BLE_STATUS_PIN GPIO_Pin_10
#define READ_BLE_STATUS GPIO_ReadInputDataBit(BLE_STATUS_PORT, BLE_STATUS_PIN)

#define BLE_PWR_PORT GPIOC
#define BLE_PWR_PIN GPIO_Pin_8
#define BLE_PWR_H GPIO_SetBits(BLE_PWR_PORT, BLE_PWR_PIN)
#define BLE_PWR_L GPIO_ResetBits(BLE_PWR_PORT, BLE_PWR_PIN)

#ifdef __cplusplus
extern "C" {
#endif

extern struct button func_key;
extern struct button rst_key;
extern u8 tamperio_state;
extern u8 system_rst;

void App_PortCfg(void);
void Test_Fout(void);
void GPIO_Sleep_Config(void);
void GPIO_OUTPUT_H(GPIO_Type *GPIOx, uint32_t GPIO_Pin);
void GPIO_OUTPUT_L(GPIO_Type *GPIOx, uint32_t GPIO_Pin);

void MOTOR_Init(void);
void MOTOR_FOREWARD(void);
void MOTOR_REVERSAL(void);
void MOTOR_STANDBY(void);
void MOTOR_BRAKE(void);

void thread_led(ULONG thread_input);
void thread_motor(ULONG thread_input);

#ifdef __cplusplus
}
#endif

#endif
