
#ifndef __GPIO_H__
#define __GPIO_H__

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include <config.h>

#define GPIO_PIN_STATUS_RESET 0
#define GPIO_PIN_STATUS_SET 1

#define ReadInputPin(x, PinMask) (READ_BIT(x->IDR, PinMask) ? GPIO_PIN_STATUS_SET : GPIO_PIN_STATUS_RESET)
#define ReadOutputPin(x, PinMask) (READ_BIT(x->ODR, PinMask) ? GPIO_PIN_STATUS_SET : GPIO_PIN_STATUS_RESET)

// ** 磁敏开关 ** //
#define VCS_INT_PIN LL_GPIO_PIN_0
#define VCS_INT_PORT GPIOA
#define VCS_INT_STA ReadInputPin(VCS_INT_PORT, VCS_INT_PIN)

// ** 蓝牙连接状态 ** //
#define BLE_CONNECT_PIN LL_GPIO_PIN_2
#define BLE_CONNECT_PORT GPIOB
#define BLE_CONNECT_STA ReadInputPin(BLE_CONNECT_PORT, BLE_CONNECT_PIN)

// ** 蜂鸣器 ** //
#define GPIO_BEEP_PIN LL_GPIO_PIN_1
#define GPIO_BEEP_PORT GPIOA
#define GPIO_BEEP_L LL_GPIO_ResetOutputPin(GPIO_BEEP_PORT, GPIO_BEEP_PIN)
#define GPIO_BEEP_H LL_GPIO_SetOutputPin(GPIO_BEEP_PORT, GPIO_BEEP_PIN)

// ** LED ** //
#define GPIO_RED_LED_PIN LL_GPIO_PIN_0
#define GPIO_RED_LED_PORT GPIOB
#define GPIO_RED_LED_L LL_GPIO_ResetOutputPin(GPIO_RED_LED_PORT, GPIO_RED_LED_PIN)
#define GPIO_RED_LED_H LL_GPIO_SetOutputPin(GPIO_RED_LED_PORT, GPIO_RED_LED_PIN)

#define GPIO_BLUE_LED_PIN LL_GPIO_PIN_1
#define GPIO_BLUE_LED_PORT GPIOB
#define GPIO_BLUE_LED_L LL_GPIO_ResetOutputPin(GPIO_BLUE_LED_PORT, GPIO_BLUE_LED_PIN)
#define GPIO_BLUE_LED_H LL_GPIO_SetOutputPin(GPIO_BLUE_LED_PORT, GPIO_BLUE_LED_PIN)

// ** 插入检测 ** //
#define GPIO_INSERT1_INT_PIN LL_GPIO_PIN_6
#define GPIO_INSERT1_INT_PORT GPIOA
#define INSERT1_CONNECT_STA ReadInputPin(GPIO_INSERT1_INT_PORT, GPIO_INSERT1_INT_PIN)

#define GPIO_INSERT2_INT_PIN LL_GPIO_PIN_7
#define GPIO_INSERT2_INT_PORT GPIOA
#define INSERT2_CONNECT_STA ReadInputPin(GPIO_INSERT2_INT_PORT, GPIO_INSERT2_INT_PIN)

// ** 脉冲输入 ** //
#define GPIO_PULSE1_PIN LL_GPIO_PIN_4
#define GPIO_PULSE1_PORT GPIOA
#define PULSE1_STA ReadInputPin(GPIO_PULSE1_PORT, GPIO_PULSE1_PIN)

#define GPIO_PULSE2_PIN LL_GPIO_PIN_5
#define GPIO_PULSE2_PORT GPIOA
#define PULSE2_STA ReadInputPin(GPIO_PULSE2_PORT, GPIO_PULSE2_PIN)

// ** 电磁阀电源升压切换 ** //
#define GPIO_5V_PWR_PIN LL_GPIO_PIN_3
#define GPIO_5V_PWR_PORT GPIOB
#define GPIO_5V_PWR_L LL_GPIO_ResetOutputPin(GPIO_5V_PWR_PORT, GPIO_5V_PWR_PIN)
#define GPIO_5V_PWR_H LL_GPIO_SetOutputPin(GPIO_5V_PWR_PORT, GPIO_5V_PWR_PIN)

#define GPIO_9V_PWR_PIN LL_GPIO_PIN_8
#define GPIO_9V_PWR_PORT GPIOB
#define GPIO_9V_PWR_L LL_GPIO_ResetOutputPin(GPIO_9V_PWR_PORT, GPIO_9V_PWR_PIN)
#define GPIO_9V_PWR_H LL_GPIO_SetOutputPin(GPIO_9V_PWR_PORT, GPIO_9V_PWR_PIN)

#define GPIO_12V_PWR_PIN LL_GPIO_PIN_9
#define GPIO_12V_PWR_PORT GPIOB
#define GPIO_12V_PWR_L LL_GPIO_ResetOutputPin(GPIO_12V_PWR_PORT, GPIO_12V_PWR_PIN)
#define GPIO_12V_PWR_H LL_GPIO_SetOutputPin(GPIO_12V_PWR_PORT, GPIO_12V_PWR_PIN)

// ** 电磁阀电源输出 ** //
#define GPIO_BOOST_PWR_PIN LL_GPIO_PIN_15
#define GPIO_BOOST_PWR_PORT GPIOB
#define GPIO_BOOST_PWR_L LL_GPIO_ResetOutputPin(GPIO_BOOST_PWR_PORT, GPIO_BOOST_PWR_PIN)
#define GPIO_BOOST_PWR_H LL_GPIO_SetOutputPin(GPIO_BOOST_PWR_PORT, GPIO_BOOST_PWR_PIN)

// ** 电磁阀控制 ** //
#define GPIO_CON1_EN_PIN LL_GPIO_PIN_3
#define GPIO_CON1_EN_PORT GPIOC
#define GPIO_CON1_EN_L LL_GPIO_ResetOutputPin(GPIO_CON1_EN_PORT, GPIO_CON1_EN_PIN)
#define GPIO_CON1_EN_H LL_GPIO_SetOutputPin(GPIO_CON1_EN_PORT, GPIO_CON1_EN_PIN)

#define GPIO_CON1_A_PIN LL_GPIO_PIN_1
#define GPIO_CON1_A_PORT GPIOC
#define GPIO_CON1_A_L LL_GPIO_ResetOutputPin(GPIO_CON1_A_PORT, GPIO_CON1_A_PIN)
#define GPIO_CON1_A_H LL_GPIO_SetOutputPin(GPIO_CON1_A_PORT, GPIO_CON1_A_PIN)

#define GPIO_CON1_B_PIN LL_GPIO_PIN_2
#define GPIO_CON1_B_PORT GPIOC
#define GPIO_CON1_B_L LL_GPIO_ResetOutputPin(GPIO_CON1_B_PORT, GPIO_CON1_B_PIN)
#define GPIO_CON1_B_H LL_GPIO_SetOutputPin(GPIO_CON1_B_PORT, GPIO_CON1_B_PIN)

#define GPIO_CON2_EN_PIN LL_GPIO_PIN_14
#define GPIO_CON2_EN_PORT GPIOB
#define GPIO_CON2_EN_L LL_GPIO_ResetOutputPin(GPIO_CON2_EN_PORT, GPIO_CON2_EN_PIN)
#define GPIO_CON2_EN_H LL_GPIO_SetOutputPin(GPIO_CON2_EN_PORT, GPIO_CON2_EN_PIN)

#define GPIO_CON2_A_PIN LL_GPIO_PIN_12
#define GPIO_CON2_A_PORT GPIOB
#define GPIO_CON2_A_L LL_GPIO_ResetOutputPin(GPIO_CON2_A_PORT, GPIO_CON2_A_PIN)
#define GPIO_CON2_A_H LL_GPIO_SetOutputPin(GPIO_CON2_A_PORT, GPIO_CON2_A_PIN)

#define GPIO_CON2_B_PIN LL_GPIO_PIN_13
#define GPIO_CON2_B_PORT GPIOB
#define GPIO_CON2_B_L LL_GPIO_ResetOutputPin(GPIO_CON2_B_PORT, GPIO_CON2_B_PIN)
#define GPIO_CON2_B_H LL_GPIO_SetOutputPin(GPIO_CON2_B_PORT, GPIO_CON2_B_PIN)

// ** FLASH ** //
#define FLASH_WP_PIN LL_GPIO_PIN_4
#define FLASH_WP_PORT GPIOB
#define FLASH_WP_L LL_GPIO_ResetOutputPin(FLASH_WP_PORT, FLASH_WP_PIN)
#define FLASH_WP_H LL_GPIO_SetOutputPin(FLASH_WP_PORT, FLASH_WP_PIN)

#define FLASH_HOLD_PIN LL_GPIO_PIN_3
#define FLASH_HOLD_PORT GPIOB
#define FLASH_HOLD_L LL_GPIO_ResetOutputPin(FLASH_HOLD_PORT, FLASH_HOLD_PIN)
#define FLASH_HOLD_H LL_GPIO_SetOutputPin(FLASH_HOLD_PORT, FLASH_HOLD_PIN)

// ** LoRaWAN ** //
#define LoRaWAN_WAKE_PIN LL_GPIO_PIN_8
#define LoRaWAN_WAKE_PORT GPIOA
#define LoRaWAN_WAKE_STA ReadOutputPin(LoRaWAN_WAKE_PORT, LoRaWAN_WAKE_PIN)
#define LoRaWAN_WAKE_L LL_GPIO_ResetOutputPin(LoRaWAN_WAKE_PORT, LoRaWAN_WAKE_PIN)
#define LoRaWAN_WAKE_H LL_GPIO_SetOutputPin(LoRaWAN_WAKE_PORT, LoRaWAN_WAKE_PIN)

#define LoRaWAN_STAT_PIN LL_GPIO_PIN_9
#define LoRaWAN_STAT_PORT GPIOC
#define LoRaWAN_STAT_STA ReadInputPin(LoRaWAN_STAT_PORT, LoRaWAN_STAT_PIN)

#define LoRaWAN_BUSY_PIN LL_GPIO_PIN_8
#define LoRaWAN_BUSY_PORT GPIOC
#define LoRaWAN_BUSY_STA ReadInputPin(LoRaWAN_BUSY_PORT, LoRaWAN_BUSY_PIN)

#define LoRaWAN_MODE_PIN LL_GPIO_PIN_7
#define LoRaWAN_MODE_PORT GPIOC
#define LoRaWAN_MODE_STA ReadOutputPin(LoRaWAN_MODE_PORT, LoRaWAN_MODE_PIN)
#define LoRaWAN_MODE_L LL_GPIO_ResetOutputPin(LoRaWAN_MODE_PORT, LoRaWAN_MODE_PIN)
#define LoRaWAN_MODE_H LL_GPIO_SetOutputPin(LoRaWAN_MODE_PORT, LoRaWAN_MODE_PIN)

#define LoRaWAN_NRST_PIN LL_GPIO_PIN_6
#define LoRaWAN_NRST_PORT GPIOC
#define LoRaWAN_NRST_L LL_GPIO_ResetOutputPin(LoRaWAN_NRST_PORT, LoRaWAN_NRST_PIN)
#define LoRaWAN_NRST_H LL_GPIO_SetOutputPin(LoRaWAN_NRST_PORT, LoRaWAN_NRST_PIN)

#define LoRaWAN_IRQ_PIN LL_GPIO_PIN_11
#define LoRaWAN_IRQ_PORT GPIOA
#define LoRaWAN_IRQ_STA ReadInputPin(LoRaWAN_IRQ_PORT, LoRaWAN_IRQ_PIN)

void Beep(int time);
void port_sleep_init(void);
void App_PortCfg(void);
void GpioEventProcess(void);

void back_1_control(void);
void back_2_control(void);
void forward_1_control(void);
void forward_2_control(void);

#ifdef __cplusplus
}
#endif

#endif
