brokerClusterName: DeviceHubCluster
brokerName: broker-a
brokerId: 0
# Remote consumers connect via this advertised address.
brokerIP1: 172.17.10.206
listenPort: 10911
namesrvAddr: rmqnamesrv:9876
deleteWhen: 04
fileReservedTime: 48
brokerRole: ASYNC_MASTER
flushDiskType: ASYNC_FLUSH
autoCreateTopicEnable: true
autoCreateSubscriptionGroup: true
storePathRootDir: /home/rocketmq/store
storePathCommitLog: /home/rocketmq/store/commitlog
